//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserMangementTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public int Id { get; set; }
        public Nullable<int> UserInOrgId { get; set; }
        public Nullable<int> DepId { get; set; }
        public string Type { get; set; }
    
        public virtual UserInOrg UserInOrg { get; set; }
        public virtual department department { get; set; }
    }
}
