//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserMangementTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInRegistry
    {
        public int Id { get; set; }
        public int UserInOrgId { get; set; }
        public System.DateTime TimeLogIn { get; set; }
    
        public virtual UserInOrg UserInOrg { get; set; }
    }
}
