//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserMangementTemplate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UMDataBaseEntitiesConnection : DbContext
    {
        public UMDataBaseEntitiesConnection()
            : base("name=UMDataBaseEntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auth> Auth { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<DepPointer> DepPointer { get; set; }
        public virtual DbSet<LogInRegistry> LogInRegistry { get; set; }
        public virtual DbSet<Org> Org { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<TeamMember> TeamMember { get; set; }
        public virtual DbSet<TeamPointer> TeamPointer { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserInOrg> UserInOrg { get; set; }
    }
}
